const langData = {
  en: {
    language: "English",
    other: "Azərbaycan",
    aboutUs: {
      header: "Buy glasses at Luminoos.",
      firstText:
        "Welcome to Luminoos, where style meets vision! We're not just about          eyewear; we're about helping you see the world in a whole new light,          while looking fabulous doing it. Our passion for eyeglasses goes          beyond functionality; it's about expressing your unique personality          and enhancing your everyday experiences.",
      mainHeader: "Our Story",
      mainText:
        "Our journey began with a simple vision: to provide top-quality              eyewear that combines fashion and function. Founded by a team of              eyewear enthusiasts, Luminoos has evolved into              a trusted destination for trendy eyeglasses and sunglasses. As eyewear connoisseurs ourselves, we understand the importance of              finding the perfect pair. Whether you're seeking the latest              fashion trends, timeless classics, or specialized prescription              glasses, we've got you covered. Our carefully curated collection              features a wide range of styles, colors, and materials to suit              every taste and need.",
    },
    account: {
      name: "Name",
      errorName: "Only letters!",
      email: "Email",
      errorEmail: "Wrong email!",
      password: "Password",
      errorPassword:
        "Minimum eight characters, at least one letter       and one number!",
      button: "Update account",
    },
    bestSeller: {
      header: "Bestseller",
    },
    blog: {
      header: "Blogs",
      error: "Should not be empty!",
      crtBtn: "Create",
      dltBtn: "Delete",
      updBtn: "Update",
      detailHeader: "Other Blogs",
      id: "Id",
      image: "Image",
      date: "Date",
      headerItem: "Header",
      answer: "Answer",
      button: "button",
      edit: "edit",
      blogAnswer:
        "Not sure what your glasses measurements are or how to find them? Keep       reading, you’ll find all the information you need! The...",
      actBtn: "Go to",
    },
    cart: {
      error: "Wrong code",
      header: "Your Cart",
      item: "product",
      sum: "Total",
      code: "Enter promo code",
      codeBtn: "Get discount",
      mainBtn: "Buy",
      empty: "Your cart is empty",
      emptyBtn: "Continue Shopping",
    },
    contactUs: {},
    details: {
      formHeader: "Add review",
      rate: "Rate:",
      rateError: "Please rate",
      error: "Should not be empty",
      name: "Name",
      descriptionReview: "description",
      formBtn: "Send",
      reviewHeader: "Reviews",
      linkReview: "Write a review",
      new: "Hot",
      color: "Color",
      description:
        "These oval glasses are flexible and lightweight for all-day comfort. The medium-wide acetate frame features matte turquoise textured embellishments on the outside corners of the frame that match the temple arms.",
      priceHeader: "Price includes",
      include1: "Frame & cleaning cloth",
      include2: "Quality 1.5 index lenses",
      mainBtn1: "Add to Cart",
      mainBtn2: "Remove from Cart",
    },
    faq: "Hey! Have any questions?",
    footer: {
      copyright: " Copyright 2023 | Luminoos By Duman. All rights reserved.",
      category: {
        header: "Category",
        link1: "Sunglasses",
        link2: "Game glasses",
        link3: "Eyeglasses",
      },
      information: {
        header: "Information",
        link1: "About Us",
        link2: "Contact Us",
        link3: "FAQ",
      },
      others: { header: "Others", link1: "Service" },
    },
    special: "Products",
    login: {
      email: "Email",
      errorEmail: "Wrong email!",
      password: "Password",
      errorPassword1: "Wrong password!",
      forgot: "Forgot your password?",
      registerLink: "Don’t have an account?",
      register: "Sign Up",
      name: "Name",
      errorName: "Only letters!",
      errorPassword2:
        "Minimum eight characters, at least one letter and one number!",
      signLink: "Already a member?",
      sign: "Sign In",
    },
    navbar: {
      link1: "Sunglasses",
      link2: "Game glasses",
      link3: "Eyeglasses",
      link4: "Service",
    },
    notFound: {
      header: "Oops! That Page Can’t Be Found.",
      text: "THE PAGE YOU ARE LOOKING FOR DOES NOT EXITS",
      link: " Home page",
      linkText: "Please return to ",
    },
    products: {
      error: "Should not be empty!",
      image: "Image",
      discount: "Discount",
      bestSeller: "BestSeller",
      hot: "Hot",
      name: "Name",
      brand: "Brand",
      typeEn: "TypeEn",
      price: "Price",
      genderEn: "GenderEn",
      colorEn: "ColorEn",
      typeAz: "TypeAz",
      colorAz: "ColorAz",
      genderAz: "GenderAz",
      crtBtn: "Create",
      dltBtn: "Delete",
      updBtn: "Update",
    },
    profile: {
      header: "Welcome Back",
      link1: "My Account",
      link2: "Products",
      link3: "Blogs",
      link4: "Sign Out",
    },
    recommend: { header: "Recommend" },
    search: "Wait...",
    section: {
      link1: "Products",
      link2: "Blogs",
      cart: "Cart",
      wishlist: "Wishlist",
      login: "Login",
    },
    service: {},
    sort: {
      price: "Price",
      hot: "Hot",
      men: "Men",
      women: "Women",
      gender: "Gender",
      color: "Color",
      yellow: "Yellow",
      black: "Black",
      brown: "Brown",
      blue: "Blue",
      gray: "Gray",
      green: "Green",
      orange: "Orange",
      pink: "Pink",
      brand: "Brand",
      layout: "Layout",
      cheap: "Cheap at first",
      expensive: "Expensive at first",
      btn: "Search",
    },
    empty: "No matching products were found",
    thank: {
      text: "Thank you for shopping with us.",
      btn: "Continue shopping",
    },
    wishlist: {
      header: "Your Wishlist",
      empty: "Your wishlist is empty",
      emptyBtn: "Continue Shopping",
    },
  },
  az: {
    language: "Azərbaycan",
    other: "English",
    aboutUs: {
      header: "Luminoos-da eynək alın.",
      firstText:
        "Stilin görmə ilə qovuşduğu Luminoos-a xoş gəlmisiniz! Biz təkcə gözlüklə bağlı deyilik; Biz sizə dünyanı tamamilə yeni bir işıqda görməyə kömək etmək istəyirik, eyni zamanda bunu etmək inanılmaz görünür. Eynəklərə olan həvəsimiz funksionallıqdan kənara çıxır; unikal şəxsiyyətinizi ifadə etmək və gündəlik təcrübənizi artırmaqdır.",
      mainHeader: "Bizim Hekayəmiz",
      mainText:
        "Səyahətimiz sadə bir baxışla başladı: moda və funksiyanı birləşdirən yüksək keyfiyyətli eynək təmin etmək. Eynək həvəskarları komandası tərəfindən qurulan Luminoos dəbli eynəklər və gün eynəkləri üçün etibarlı bir məkana çevrildi. Eynək biliciləri olaraq biz mükəmməl cütü tapmağın vacibliyini başa düşürük. İstər ən son dəb tendensiyalarını, istər köhnəlməz klassikləri, istərsə də xüsusi reseptli eynəkləri axtarırsınızsa, biz sizi əhatə etdik. Diqqətlə tərtib edilmiş kolleksiyamız hər zövqə və ehtiyaca uyğun geniş üslub, rəng və materiallara malikdir.",
    },
    account: {
      name: "Ad",
      errorName: "Yalnız hərflər!",
      email: "E-poçt",
      errorEmail: "Səhv e-poçt!",
      password: "Parol",
      errorPassword: "Minimum 8 simvol, ən azı 1 hərf  və bir nömrə!",
      button: "Hesabı yeniləyin",
    },
    bestSeller: {
      header: "Ən çox satan",
    },
    blog: {
      header: "Bloqlar",
      error: "Boş olmamalıdır!",
      crtBtn: "Yaradın",
      dltBtn: "Silin",
      updBtn: "Yeniləyin",
      detailHeader: "Digər Bloqlar",
      id: "İd",
      image: "Şəkil",
      date: "Tarix",
      headerItem: "Başlıq",
      answer: "Cavab verin",
      button: "Keçid",
      edit: "Düzəliş",
      blogAnswer:
        "Eynəyinizin ölçülərinin nə olduğuna və ya onları necə tapacağınıza əmin deyilsiniz? Oxumağa davam edin, sizə lazım olan bütün məlumatları tapacaqsınız! Tapacaqsınız...",
      actBtn: "Keçid",
    },
    cart: {
      error: "Səhv kod",
      header: "Kartınız",
      item: "məhsul",
      sum: "Ümumi",
      code: "Promo kodu daxil edin",
      codeBtn: "Endirim əldə edin",
      mainBtn: "Almaq",
      empty: "Kartınız boşdur",
      emptyBtn: "Almağa davam edin",
    },
    contactUs: {},
    details: {
      formHeader: "Rəy əlavə et",
      rate: "Qiymətləndir:",
      rateError: "Zəhmət olmasa qiymətləndir",
      error: "Boş olmamlıdır",
      name: "Ad",
      descriptionReview: "Təsvir",
      formBtn: "Göndər",
      reviewHeader: "Şərhlər",
      linkReview: "Rəy yaz",
      new: "Yeni",
      color: "Rəng",
      description:
        "Bu oval eynəklər gün boyu rahatlıq üçün əyilə bilən və yüngüldür. Narahatlıq yaratmayan asetat çərçivəli eynəklərdə çərçivənin xarici künclərində tutqun firuzəyi toxumalı bəzəklər var.",
      priceHeader: "Qiymətə daxildir",
      include1: "Çərçivə və təmizləyici parça",
      include2: "Keyfiyyətli 1.5 indeksli linzalar",
      mainBtn1: "Səbətə əlavə et",
      mainBtn2: "Səbətdən çıxarın",
    },
    faq: "Hey! Hər hansı bir sualınız var?",
    footer: {
      copyright:
        "Müəllif hüququ 2023 | Duman tərəfindən Luminoos. Bütün hüquqlar qorunur.",
      category: {
        header: "Kateqoriya",
        link1: "Günəş eynəkləri",
        link2: "Oyun eynəkləri",
        link3: "Göz eynəkləri",
      },
      information: {
        header: "Məlumat",
        link1: "Haqqımızda",
        link2: "Əlaqə",
        link3: "Sual-Cavab",
      },
      others: { header: "Digərlər", link1: "Xidmət" },
    },
    special: "Məhsullar",
    login: {
      email: "Email",
      errorEmail: "Səhv email!",
      password: "Parol",
      errorPassword1: "Səhv password!",
      forgot: "Parolu unutdun?",
      registerLink: "Hesabın yoxdur?",
      register: "Hesab yarat",
      name: "Ad",
      errorName: "Yalnız hərflər!",
      errorPassword2: "Minimum səkkiz simvol, ən azı bir hərf və bir rəqəm!",
      signLink: "Artıq üzvsən?",
      sign: "Giriş et",
    },
    navbar: {
      link1: "Günəş eynəkləri",
      link2: "Oyun eynəkləri",
      link3: "Göz eynəkləri",
      link4: "Təmir",
    },
    notFound: {
      link: " Əsas səhifə",
      header: "Oops! O Səhifəni Tapmaq Mümkün deyil.",
      text: "AXTADIĞINIZ SƏHİFƏ ÇIXMIR",
      linkText: "Zəhmət olmasa qayıdın",
    },
    products: {
      error: "Boş olmamalıdır!",
      image: "Şəkil",
      discount: "Endirim",
      bestSeller: "Ən çox satan",
      hot: "Yeni",
      name: "Ad",
      brand: "Brend",
      typeEn: "TipEn",
      price: "Qiymət",
      genderEn: "CinsEn",
      colorEn: "RəngEn",
      typeAz: "TipAz",
      colorAz: "RəngAz",
      genderAz: "CinsAz",
      crtBtn: "Yaradın",
      dltBtn: "Silin",
      updBtn: "Yeniləyin",
    },
    profile: {
      header: "Xoş gəlmisiniz",
      link1: "Mənim Hesabım",
      link2: "Məhsullar",
      link3: "Bloqlar",
      link4: "Çıxış",
    },
    recommend: { header: "Tövsiyə edin" },
    search: "Gözləyin...",
    section: {
      link1: "Məhsullar",
      link2: "Bloqlar",
      cart: "Səbət",
      wishlist: "Bəyəndiklərim",
      login: "Daxil ol",
    },
    service: {},
    sort: {
      price: "Qiymət",
      hot: "Yeni",
      men: "Kişi",
      women: "Qadın",
      gender: "Cins",
      color: "Rəng",
      yellow: "Sarı",
      black: "Qara",
      brown: "Qəhvəyi",
      blue: "Göy",
      gray: "Boz",
      green: "Yaşıl",
      orange: "Narıncı",
      pink: "Çəhrayı",
      brand: "Brend",
      layout: "Düzülüş",
      cheap: "Əvvəlcə ucuz",
      expensive: "Əvvəlcə bahalı",
      btn: "Axtar",
    },
    empty: "Uyğun məhsul tapılmadı",
    thank: {
      text: "Bizimlə alış-veriş etdiyiniz üçün təşəkkür edirik.",
      btn: "Alış-verişə davam edin",
    },
    wishlist: {
      header: "Bəyəndikləriniz",
      empty: "Sizin bəyəndikləriniz boşdur",
      emptyBtn: "Alış-verişə davam edin",
    },
  },
};

export default langData;
